### ISSUE TITLE
Checkin of --interactive / --nointeractive doesn't seem to work

### ISSUE THREAD

**Issue by bdenison99** [Microsoft/StorScore#23]
I specified a target and recipe file, and got the following with ActiveState Perl:

Error "Can't locate object method "interactive" via package "CommandLine" at C:\Users\A
dministrator.MICRONSTORAGE\Desktop\StorScore-master\StorScore.cmd line 208."

If I add --interactive or --nointeractive, I get back unknown option text like the following:
StorScore.cmd --target=\.\physicaldrive1 --recipe=recipes\turkey_test.rcp --interactive returns "Unknown option: interactive"

**Comment by lauracaulfield** [comment]
Sorry about that -- looks like I missed one of the changed files.  The latest code should work now.

**Comment by bdenison99** [comment]
Thank you!  Much better!
