### ISSUE TITLE
Precondition.exe hangs when run on >2TB targets

### ISSUE THREAD

**Issue by bdenison99** [Microsoft/StorScore#30]
In precondition.cpp:
The following line numbers and variable names need to change from int to int64_t:
Line 39:  outstandingIOs
Line 419: postedIOs
Line 420: completedIOs
Line 428: TOTAL_BLOCKS

**Comment by marksantaniello** [comment]
Thanks for opening this.  

To be clear, the overflow occurs when we have more than (2^31)-1 blocks in the target.   Disks themselves are often measured in base-10, but our blocks are base-2.  So a 2 TB (2*10^12) file with 1 KiB (2^10) blocks might actually work, but just barely.  Also a 2 TB file with something like 4K or larger block size will still work.

But yes -- we ought to increase those variables to 64 bits.  I should have done that in the first place.
